Lambda Layer Update : OTel Java 1.12.1
open-telemetry/opentelemetry-lambda-extension pull request #233
Opened 2022-04-06 21:55 UTC by vasireddy99

This PR updates OTel Java dependencies to 1.12.1 and other dependencies to their latest available

2022-04-27 21:49 UTC, NathanielRN approved these changes

2022-04-27 22:13 UTC, NathanielRN requested changes
It looks like there are even newer changes based on https://github.com/aws-observability/aws-otel-java-instrumentation/pull/165, sorry for not checking earlier, do you want to update to these all at once?

2022-04-27 22:14 UTC, vasireddy99 commented
> It looks like there are even newer changes based on [aws-observability/aws-otel-java-instrumentation#165](https://github.com/aws-observability/aws-otel-java-instrumentation/pull/165), sorry for not checking earlier, do you want to update to these all at once?

sure Nathaniel, updating them

2022-04-28 20:10 UTC, NathanielRN approved these changes

2022-04-28 20:10 UTC, merged